/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package wtx.symfonia.api.client;

import wtx.symfonia.api.client.invoker.ApiCallback;
import wtx.symfonia.api.client.invoker.ApiClient;
import wtx.symfonia.api.client.invoker.ApiException;
import wtx.symfonia.api.client.invoker.ApiResponse;
import wtx.symfonia.api.client.invoker.Configuration;
import wtx.symfonia.api.client.invoker.Pair;
import wtx.symfonia.api.client.invoker.ProgressRequestBody;
import wtx.symfonia.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import wtx.symfonia.api.client.model.ApiError;
import wtx.symfonia.api.client.model.InventoryState;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InventoryStatesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InventoryStatesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InventoryStatesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getInventoryStates
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych dla wszystkich magazynow i towarow InventoryState. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInventoryStatesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/InventoryStates";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInventoryStatesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getInventoryStatesCall(_callback);

    }

    /**
     * Metoda umozliwia pobranie wszystkich stanow magazynowych i handlowych dla wszystkich magazynow i towarow.
     * 
     * @return List&lt;InventoryState&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych dla wszystkich magazynow i towarow InventoryState. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public List<InventoryState> getInventoryStates() throws ApiException {
        ApiResponse<List<InventoryState>> localVarResp = getInventoryStatesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Metoda umozliwia pobranie wszystkich stanow magazynowych i handlowych dla wszystkich magazynow i towarow.
     * 
     * @return ApiResponse&lt;List&lt;InventoryState&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych dla wszystkich magazynow i towarow InventoryState. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<InventoryState>> getInventoryStatesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getInventoryStatesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<InventoryState>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Metoda umozliwia pobranie wszystkich stanow magazynowych i handlowych dla wszystkich magazynow i towarow. (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych dla wszystkich magazynow i towarow InventoryState. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInventoryStatesAsync(final ApiCallback<List<InventoryState>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInventoryStatesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<InventoryState>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getInventoryStatesByProduct
     * @param id Identyfikator towaru. (optional)
     * @param code Kod towaru. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych InventoryState. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInventoryStatesByProductCall(String id, String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/InventoryStates/ByProduct";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        if (code != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("code", code));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInventoryStatesByProductValidateBeforeCall(String id, String code, final ApiCallback _callback) throws ApiException {
        return getInventoryStatesByProductCall(id, code, _callback);

    }

    /**
     * Metoda umozliwia pobranie stanow magazynowych i handlowych ze wszystkich magazynow dla towaru o podanym identyfikatorze lub kodzie.
     * 
     * @param id Identyfikator towaru. (optional)
     * @param code Kod towaru. (optional)
     * @return List&lt;InventoryState&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych InventoryState. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public List<InventoryState> getInventoryStatesByProduct(String id, String code) throws ApiException {
        ApiResponse<List<InventoryState>> localVarResp = getInventoryStatesByProductWithHttpInfo(id, code);
        return localVarResp.getData();
    }

    /**
     * Metoda umozliwia pobranie stanow magazynowych i handlowych ze wszystkich magazynow dla towaru o podanym identyfikatorze lub kodzie.
     * 
     * @param id Identyfikator towaru. (optional)
     * @param code Kod towaru. (optional)
     * @return ApiResponse&lt;List&lt;InventoryState&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych InventoryState. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<InventoryState>> getInventoryStatesByProductWithHttpInfo(String id, String code) throws ApiException {
        okhttp3.Call localVarCall = getInventoryStatesByProductValidateBeforeCall(id, code, null);
        Type localVarReturnType = new TypeToken<List<InventoryState>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Metoda umozliwia pobranie stanow magazynowych i handlowych ze wszystkich magazynow dla towaru o podanym identyfikatorze lub kodzie. (asynchronously)
     * 
     * @param id Identyfikator towaru. (optional)
     * @param code Kod towaru. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca kolekcje obiektow stanow magazynowych i handlowych InventoryState. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInventoryStatesByProductAsync(String id, String code, final ApiCallback<List<InventoryState>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInventoryStatesByProductValidateBeforeCall(id, code, _callback);
        Type localVarReturnType = new TypeToken<List<InventoryState>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
