/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.symfonia.api.client;

import pl.wtx.symfonia.api.client.invoker.ApiCallback;
import pl.wtx.symfonia.api.client.invoker.ApiClient;
import pl.wtx.symfonia.api.client.invoker.ApiException;
import pl.wtx.symfonia.api.client.invoker.ApiResponse;
import pl.wtx.symfonia.api.client.invoker.Configuration;
import pl.wtx.symfonia.api.client.invoker.Pair;
import pl.wtx.symfonia.api.client.invoker.ProgressRequestBody;
import pl.wtx.symfonia.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.symfonia.api.client.model.ApiError;
import pl.wtx.symfonia.api.client.model.Order;
import pl.wtx.symfonia.api.client.model.OrderIssue;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrdersIssueApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrdersIssueApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrdersIssueApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addNewOrdersIssue
     * @param orderIssue  (required)
     * @param issue Czy wystawic zamowienie obce. W przypadku, gdy parametr nie zostanie podany zamowienie obce zostanie wystawione. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca obiekt wystawionego zamowienia Order. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addNewOrdersIssueCall(OrderIssue orderIssue, Boolean issue, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = orderIssue;

        // create path and map variables
        String localVarPath = "/OrdersIssue/New";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (issue != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("issue", issue));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addNewOrdersIssueValidateBeforeCall(OrderIssue orderIssue, Boolean issue, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orderIssue' is set
        if (orderIssue == null) {
            throw new ApiException("Missing the required parameter 'orderIssue' when calling addNewOrdersIssue(Async)");
        }

        return addNewOrdersIssueCall(orderIssue, issue, _callback);

    }

    /**
     * Metoda umozliwia wystawienie nowego zamowienia obcego.
     * 
     * @param orderIssue  (required)
     * @param issue Czy wystawic zamowienie obce. W przypadku, gdy parametr nie zostanie podany zamowienie obce zostanie wystawione. (optional)
     * @return Order
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca obiekt wystawionego zamowienia Order. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public Order addNewOrdersIssue(OrderIssue orderIssue, Boolean issue) throws ApiException {
        ApiResponse<Order> localVarResp = addNewOrdersIssueWithHttpInfo(orderIssue, issue);
        return localVarResp.getData();
    }

    /**
     * Metoda umozliwia wystawienie nowego zamowienia obcego.
     * 
     * @param orderIssue  (required)
     * @param issue Czy wystawic zamowienie obce. W przypadku, gdy parametr nie zostanie podany zamowienie obce zostanie wystawione. (optional)
     * @return ApiResponse&lt;Order&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca obiekt wystawionego zamowienia Order. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Order> addNewOrdersIssueWithHttpInfo(OrderIssue orderIssue, Boolean issue) throws ApiException {
        okhttp3.Call localVarCall = addNewOrdersIssueValidateBeforeCall(orderIssue, issue, null);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Metoda umozliwia wystawienie nowego zamowienia obcego. (asynchronously)
     * 
     * @param orderIssue  (required)
     * @param issue Czy wystawic zamowienie obce. W przypadku, gdy parametr nie zostanie podany zamowienie obce zostanie wystawione. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Zwraca obiekt wystawionego zamowienia Order. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addNewOrdersIssueAsync(OrderIssue orderIssue, Boolean issue, final ApiCallback<Order> _callback) throws ApiException {

        okhttp3.Call localVarCall = addNewOrdersIssueValidateBeforeCall(orderIssue, issue, _callback);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
