/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.symfonia.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.symfonia.api.client.invoker.JSON;

/**
 * ContractorCriteriaFilter
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class ContractorCriteriaFilter {
  public static final String SERIALIZED_NAME_ACTIVE = "Active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Boolean active;

  public static final String SERIALIZED_NAME_CATALOG_ID = "CatalogId";
  @SerializedName(SERIALIZED_NAME_CATALOG_ID)
  @javax.annotation.Nullable
  private Integer catalogId;

  public static final String SERIALIZED_NAME_KIND_ID = "KindId";
  @SerializedName(SERIALIZED_NAME_KIND_ID)
  @javax.annotation.Nullable
  private Integer kindId;

  public ContractorCriteriaFilter() {
  }

  public ContractorCriteriaFilter active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Kryterium wyszukiwania po statusie aktywnosci kontrahenta. Jezeli wartosc bedzie pusta to kryterium wyszukiwania zostanie pominiete.
   * @return active
   */
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public ContractorCriteriaFilter catalogId(@javax.annotation.Nullable Integer catalogId) {
    this.catalogId = catalogId;
    return this;
  }

  /**
   * Kryterium wyszukiwania po id katalogu kontrahenta. Jezeli wartosc bedzie pusta to kryterium wyszukiwania zostanie pominiete.
   * @return catalogId
   */
  @javax.annotation.Nullable
  public Integer getCatalogId() {
    return catalogId;
  }

  public void setCatalogId(@javax.annotation.Nullable Integer catalogId) {
    this.catalogId = catalogId;
  }


  public ContractorCriteriaFilter kindId(@javax.annotation.Nullable Integer kindId) {
    this.kindId = kindId;
    return this;
  }

  /**
   * Kryterium wyszukiwania po id rodzaju kontrahenta. Jezeli wartosc bedzie pusta to kryterium wyszukiwania zostanie pominiete.
   * @return kindId
   */
  @javax.annotation.Nullable
  public Integer getKindId() {
    return kindId;
  }

  public void setKindId(@javax.annotation.Nullable Integer kindId) {
    this.kindId = kindId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractorCriteriaFilter contractorCriteriaFilter = (ContractorCriteriaFilter) o;
    return Objects.equals(this.active, contractorCriteriaFilter.active) &&
        Objects.equals(this.catalogId, contractorCriteriaFilter.catalogId) &&
        Objects.equals(this.kindId, contractorCriteriaFilter.kindId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, catalogId, kindId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractorCriteriaFilter {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    catalogId: ").append(toIndentedString(catalogId)).append("\n");
    sb.append("    kindId: ").append(toIndentedString(kindId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("Active", "CatalogId", "KindId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContractorCriteriaFilter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContractorCriteriaFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContractorCriteriaFilter is not found in the empty JSON string", ContractorCriteriaFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContractorCriteriaFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContractorCriteriaFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContractorCriteriaFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContractorCriteriaFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContractorCriteriaFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContractorCriteriaFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<ContractorCriteriaFilter>() {
           @Override
           public void write(JsonWriter out, ContractorCriteriaFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContractorCriteriaFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContractorCriteriaFilter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContractorCriteriaFilter
   * @throws IOException if the JSON string is invalid with respect to ContractorCriteriaFilter
   */
  public static ContractorCriteriaFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContractorCriteriaFilter.class);
  }

  /**
   * Convert an instance of ContractorCriteriaFilter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

