/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.symfonia.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import pl.wtx.symfonia.api.client.invoker.JSON;

import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * InventoryState
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class InventoryState {
  public static final String SERIALIZED_NAME_PRODUCT_ID = "ProductId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private Integer productId;

  public static final String SERIALIZED_NAME_WAREHOUSE_ID = "WarehouseId";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_ID)
  @javax.annotation.Nullable
  private Integer warehouseId;

  public static final String SERIALIZED_NAME_AMOUNT_IN_STORE = "AmountInStore";
  @SerializedName(SERIALIZED_NAME_AMOUNT_IN_STORE)
  @javax.annotation.Nullable
  private Double amountInStore;

  public static final String SERIALIZED_NAME_AMOUNT_TO_SALE = "AmountToSale";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TO_SALE)
  @javax.annotation.Nullable
  private Double amountToSale;

  public InventoryState() {
  }

  public InventoryState productId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Id towaru.
   * @return productId
   */
  @javax.annotation.Nullable
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  public InventoryState warehouseId(@javax.annotation.Nullable Integer warehouseId) {
    this.warehouseId = warehouseId;
    return this;
  }

  /**
   * Id magazynu.
   * @return warehouseId
   */
  @javax.annotation.Nullable
  public Integer getWarehouseId() {
    return warehouseId;
  }

  public void setWarehouseId(@javax.annotation.Nullable Integer warehouseId) {
    this.warehouseId = warehouseId;
  }


  public InventoryState amountInStore(@javax.annotation.Nullable Double amountInStore) {
    this.amountInStore = amountInStore;
    return this;
  }

  /**
   * Stan towaru w magazynie - suma przyjec i wydac z magazynu.
   * @return amountInStore
   */
  @javax.annotation.Nullable
  public Double getAmountInStore() {
    return amountInStore;
  }

  public void setAmountInStore(@javax.annotation.Nullable Double amountInStore) {
    this.amountInStore = amountInStore;
  }


  public InventoryState amountToSale(@javax.annotation.Nullable Double amountToSale) {
    this.amountToSale = amountToSale;
    return this;
  }

  /**
   * Stan handlowy towaru w magazynie - czyli stan towaru po uwzglednieniu rezerwacji.
   * @return amountToSale
   */
  @javax.annotation.Nullable
  public Double getAmountToSale() {
    return amountToSale;
  }

  public void setAmountToSale(@javax.annotation.Nullable Double amountToSale) {
    this.amountToSale = amountToSale;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryState inventoryState = (InventoryState) o;
    return Objects.equals(this.productId, inventoryState.productId) &&
        Objects.equals(this.warehouseId, inventoryState.warehouseId) &&
        Objects.equals(this.amountInStore, inventoryState.amountInStore) &&
        Objects.equals(this.amountToSale, inventoryState.amountToSale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, warehouseId, amountInStore, amountToSale);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryState {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    warehouseId: ").append(toIndentedString(warehouseId)).append("\n");
    sb.append("    amountInStore: ").append(toIndentedString(amountInStore)).append("\n");
    sb.append("    amountToSale: ").append(toIndentedString(amountToSale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProductId");
    openapiFields.add("WarehouseId");
    openapiFields.add("AmountInStore");
    openapiFields.add("AmountToSale");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InventoryState
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InventoryState.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InventoryState is not found in the empty JSON string", InventoryState.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InventoryState.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InventoryState` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InventoryState.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InventoryState' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InventoryState> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InventoryState.class));

       return (TypeAdapter<T>) new TypeAdapter<InventoryState>() {
           @Override
           public void write(JsonWriter out, InventoryState value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InventoryState read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InventoryState given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InventoryState
   * @throws IOException if the JSON string is invalid with respect to InventoryState
   */
  public static InventoryState fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InventoryState.class);
  }

  /**
   * Convert an instance of InventoryState to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

