/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.symfonia.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.symfonia.api.client.invoker.JSON;

/**
 * LoadedModuleInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class LoadedModuleInfo {
  public static final String SERIALIZED_NAME_ASSEMBLY_NAME = "AssemblyName";
  @SerializedName(SERIALIZED_NAME_ASSEMBLY_NAME)
  @javax.annotation.Nullable
  private String assemblyName;

  public static final String SERIALIZED_NAME_MODULE_NAME = "ModuleName";
  @SerializedName(SERIALIZED_NAME_MODULE_NAME)
  @javax.annotation.Nullable
  private String moduleName;

  public static final String SERIALIZED_NAME_MODULE_VERSION = "ModuleVersion";
  @SerializedName(SERIALIZED_NAME_MODULE_VERSION)
  @javax.annotation.Nullable
  private String moduleVersion;

  public LoadedModuleInfo() {
  }

  public LoadedModuleInfo assemblyName(@javax.annotation.Nullable String assemblyName) {
    this.assemblyName = assemblyName;
    return this;
  }

  /**
   * Get assemblyName
   * @return assemblyName
   */
  @javax.annotation.Nullable
  public String getAssemblyName() {
    return assemblyName;
  }

  public void setAssemblyName(@javax.annotation.Nullable String assemblyName) {
    this.assemblyName = assemblyName;
  }


  public LoadedModuleInfo moduleName(@javax.annotation.Nullable String moduleName) {
    this.moduleName = moduleName;
    return this;
  }

  /**
   * Get moduleName
   * @return moduleName
   */
  @javax.annotation.Nullable
  public String getModuleName() {
    return moduleName;
  }

  public void setModuleName(@javax.annotation.Nullable String moduleName) {
    this.moduleName = moduleName;
  }


  public LoadedModuleInfo moduleVersion(@javax.annotation.Nullable String moduleVersion) {
    this.moduleVersion = moduleVersion;
    return this;
  }

  /**
   * Get moduleVersion
   * @return moduleVersion
   */
  @javax.annotation.Nullable
  public String getModuleVersion() {
    return moduleVersion;
  }

  public void setModuleVersion(@javax.annotation.Nullable String moduleVersion) {
    this.moduleVersion = moduleVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadedModuleInfo loadedModuleInfo = (LoadedModuleInfo) o;
    return Objects.equals(this.assemblyName, loadedModuleInfo.assemblyName) &&
        Objects.equals(this.moduleName, loadedModuleInfo.moduleName) &&
        Objects.equals(this.moduleVersion, loadedModuleInfo.moduleVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assemblyName, moduleName, moduleVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadedModuleInfo {\n");
    sb.append("    assemblyName: ").append(toIndentedString(assemblyName)).append("\n");
    sb.append("    moduleName: ").append(toIndentedString(moduleName)).append("\n");
    sb.append("    moduleVersion: ").append(toIndentedString(moduleVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AssemblyName");
    openapiFields.add("ModuleName");
    openapiFields.add("ModuleVersion");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LoadedModuleInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoadedModuleInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoadedModuleInfo is not found in the empty JSON string", LoadedModuleInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LoadedModuleInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoadedModuleInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AssemblyName") != null && !jsonObj.get("AssemblyName").isJsonNull()) && !jsonObj.get("AssemblyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AssemblyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AssemblyName").toString()));
      }
      if ((jsonObj.get("ModuleName") != null && !jsonObj.get("ModuleName").isJsonNull()) && !jsonObj.get("ModuleName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ModuleName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ModuleName").toString()));
      }
      if ((jsonObj.get("ModuleVersion") != null && !jsonObj.get("ModuleVersion").isJsonNull()) && !jsonObj.get("ModuleVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ModuleVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ModuleVersion").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoadedModuleInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoadedModuleInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoadedModuleInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoadedModuleInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<LoadedModuleInfo>() {
           @Override
           public void write(JsonWriter out, LoadedModuleInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoadedModuleInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LoadedModuleInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LoadedModuleInfo
   * @throws IOException if the JSON string is invalid with respect to LoadedModuleInfo
   */
  public static LoadedModuleInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoadedModuleInfo.class);
  }

  /**
   * Convert an instance of LoadedModuleInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

