/*
 * Symfonia WebAPI
 * Symfonia WebAPI - specyfikacja wybranych endpointow API systemu ERP Symfonia. Modele danych sa uproszczone i ograniczone do niektorych parametrow (wersja rozwojowa).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.symfonia.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import pl.wtx.symfonia.api.client.invoker.JSON;
import pl.wtx.symfonia.api.client.model.SaleDocumentPosition;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * SaleDocument
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SaleDocument {
  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_DOCUMENT_NUMBER = "DocumentNumber";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_NUMBER)
  @javax.annotation.Nullable
  private String documentNumber;

  public static final String SERIALIZED_NAME_ACTIVE = "Active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Boolean active;

  public static final String SERIALIZED_NAME_ISSUE_DATE = "IssueDate";
  @SerializedName(SERIALIZED_NAME_ISSUE_DATE)
  @javax.annotation.Nullable
  private LocalDate issueDate;

  public static final String SERIALIZED_NAME_SALE_DATE = "SaleDate";
  @SerializedName(SERIALIZED_NAME_SALE_DATE)
  @javax.annotation.Nullable
  private LocalDate saleDate;

  public static final String SERIALIZED_NAME_NET_VALUE_P_L_N = "NetValuePLN";
  @SerializedName(SERIALIZED_NAME_NET_VALUE_P_L_N)
  @javax.annotation.Nullable
  private Double netValuePLN;

  public static final String SERIALIZED_NAME_VAT_VALUE_P_L_N = "VatValuePLN";
  @SerializedName(SERIALIZED_NAME_VAT_VALUE_P_L_N)
  @javax.annotation.Nullable
  private Double vatValuePLN;

  public static final String SERIALIZED_NAME_NET_VALUE = "NetValue";
  @SerializedName(SERIALIZED_NAME_NET_VALUE)
  @javax.annotation.Nullable
  private Double netValue;

  public static final String SERIALIZED_NAME_GROSS_VALUE = "GrossValue";
  @SerializedName(SERIALIZED_NAME_GROSS_VALUE)
  @javax.annotation.Nullable
  private Double grossValue;

  public static final String SERIALIZED_NAME_POSITIONS = "Positions";
  @SerializedName(SERIALIZED_NAME_POSITIONS)
  @javax.annotation.Nullable
  private List<SaleDocumentPosition> positions = new ArrayList<>();

  public SaleDocument() {
  }

  public SaleDocument id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Id dokumentu.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public SaleDocument documentNumber(@javax.annotation.Nullable String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

  /**
   * Numer dokumentu.
   * @return documentNumber
   */
  @javax.annotation.Nullable
  public String getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(@javax.annotation.Nullable String documentNumber) {
    this.documentNumber = documentNumber;
  }


  public SaleDocument active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public SaleDocument issueDate(@javax.annotation.Nullable LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

  /**
   * Get issueDate
   * @return issueDate
   */
  @javax.annotation.Nullable
  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(@javax.annotation.Nullable LocalDate issueDate) {
    this.issueDate = issueDate;
  }


  public SaleDocument saleDate(@javax.annotation.Nullable LocalDate saleDate) {
    this.saleDate = saleDate;
    return this;
  }

  /**
   * Get saleDate
   * @return saleDate
   */
  @javax.annotation.Nullable
  public LocalDate getSaleDate() {
    return saleDate;
  }

  public void setSaleDate(@javax.annotation.Nullable LocalDate saleDate) {
    this.saleDate = saleDate;
  }


  public SaleDocument netValuePLN(@javax.annotation.Nullable Double netValuePLN) {
    this.netValuePLN = netValuePLN;
    return this;
  }

  /**
   * Get netValuePLN
   * @return netValuePLN
   */
  @javax.annotation.Nullable
  public Double getNetValuePLN() {
    return netValuePLN;
  }

  public void setNetValuePLN(@javax.annotation.Nullable Double netValuePLN) {
    this.netValuePLN = netValuePLN;
  }


  public SaleDocument vatValuePLN(@javax.annotation.Nullable Double vatValuePLN) {
    this.vatValuePLN = vatValuePLN;
    return this;
  }

  /**
   * Get vatValuePLN
   * @return vatValuePLN
   */
  @javax.annotation.Nullable
  public Double getVatValuePLN() {
    return vatValuePLN;
  }

  public void setVatValuePLN(@javax.annotation.Nullable Double vatValuePLN) {
    this.vatValuePLN = vatValuePLN;
  }


  public SaleDocument netValue(@javax.annotation.Nullable Double netValue) {
    this.netValue = netValue;
    return this;
  }

  /**
   * Get netValue
   * @return netValue
   */
  @javax.annotation.Nullable
  public Double getNetValue() {
    return netValue;
  }

  public void setNetValue(@javax.annotation.Nullable Double netValue) {
    this.netValue = netValue;
  }


  public SaleDocument grossValue(@javax.annotation.Nullable Double grossValue) {
    this.grossValue = grossValue;
    return this;
  }

  /**
   * Get grossValue
   * @return grossValue
   */
  @javax.annotation.Nullable
  public Double getGrossValue() {
    return grossValue;
  }

  public void setGrossValue(@javax.annotation.Nullable Double grossValue) {
    this.grossValue = grossValue;
  }


  public SaleDocument positions(@javax.annotation.Nullable List<SaleDocumentPosition> positions) {
    this.positions = positions;
    return this;
  }

  public SaleDocument addPositionsItem(SaleDocumentPosition positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<>();
    }
    this.positions.add(positionsItem);
    return this;
  }

  /**
   * Get positions
   * @return positions
   */
  @javax.annotation.Nullable
  public List<SaleDocumentPosition> getPositions() {
    return positions;
  }

  public void setPositions(@javax.annotation.Nullable List<SaleDocumentPosition> positions) {
    this.positions = positions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleDocument saleDocument = (SaleDocument) o;
    return Objects.equals(this.id, saleDocument.id) &&
        Objects.equals(this.documentNumber, saleDocument.documentNumber) &&
        Objects.equals(this.active, saleDocument.active) &&
        Objects.equals(this.issueDate, saleDocument.issueDate) &&
        Objects.equals(this.saleDate, saleDocument.saleDate) &&
        Objects.equals(this.netValuePLN, saleDocument.netValuePLN) &&
        Objects.equals(this.vatValuePLN, saleDocument.vatValuePLN) &&
        Objects.equals(this.netValue, saleDocument.netValue) &&
        Objects.equals(this.grossValue, saleDocument.grossValue) &&
        Objects.equals(this.positions, saleDocument.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, documentNumber, active, issueDate, saleDate, netValuePLN, vatValuePLN, netValue, grossValue, positions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleDocument {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    saleDate: ").append(toIndentedString(saleDate)).append("\n");
    sb.append("    netValuePLN: ").append(toIndentedString(netValuePLN)).append("\n");
    sb.append("    vatValuePLN: ").append(toIndentedString(vatValuePLN)).append("\n");
    sb.append("    netValue: ").append(toIndentedString(netValue)).append("\n");
    sb.append("    grossValue: ").append(toIndentedString(grossValue)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Id");
    openapiFields.add("DocumentNumber");
    openapiFields.add("Active");
    openapiFields.add("IssueDate");
    openapiFields.add("SaleDate");
    openapiFields.add("NetValuePLN");
    openapiFields.add("VatValuePLN");
    openapiFields.add("NetValue");
    openapiFields.add("GrossValue");
    openapiFields.add("Positions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SaleDocument
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SaleDocument.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SaleDocument is not found in the empty JSON string", SaleDocument.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SaleDocument.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SaleDocument` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("DocumentNumber") != null && !jsonObj.get("DocumentNumber").isJsonNull()) && !jsonObj.get("DocumentNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DocumentNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DocumentNumber").toString()));
      }
      if (jsonObj.get("Positions") != null && !jsonObj.get("Positions").isJsonNull()) {
        JsonArray jsonArraypositions = jsonObj.getAsJsonArray("Positions");
        if (jsonArraypositions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Positions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Positions` to be an array in the JSON string but got `%s`", jsonObj.get("Positions").toString()));
          }

          // validate the optional field `Positions` (array)
          for (int i = 0; i < jsonArraypositions.size(); i++) {
            SaleDocumentPosition.validateJsonElement(jsonArraypositions.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SaleDocument.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SaleDocument' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SaleDocument> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SaleDocument.class));

       return (TypeAdapter<T>) new TypeAdapter<SaleDocument>() {
           @Override
           public void write(JsonWriter out, SaleDocument value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SaleDocument read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SaleDocument given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SaleDocument
   * @throws IOException if the JSON string is invalid with respect to SaleDocument
   */
  public static SaleDocument fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SaleDocument.class);
  }

  /**
   * Convert an instance of SaleDocument to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

