name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B clean package -DskipTests
          mvn -B javadoc:javadoc
          mvn -B source:jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name:
